version: "3.9"

volumes:
  laravel-dir:
  mysql-data:

services:
  laravel:
    image: sensasidelight/php-laravel:${PHP_VERSION:?}
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - laravel-dir:/var/www:delegated
      - ${APP_SRC_LOCAL:-./}:/home/${COMPOSE_PROJECT_NAME:?}/app_src:cached
      - ./.env:/var/www/.env:cached
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:${MYSQL_VERSION:?}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?}
      MYSQL_USER: ${DB_USERNAME:?}
      MYSQL_PASSWORD: ${DB_PASSWORD:?}
    volumes:
      - mysql-data:/var/lib/mysql:delegated
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  nginx:
    image: nginx:${NGINX_VERSION:?}
    restart: unless-stopped
    ports:
      - ${PORT:-80}:80
    volumes:
      - laravel-dir:/var/www:delegated
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - laravel
