version: "3.8"

networks:
  app-net:

volumes:
  laravel-dir:
  mysql-data:

services:
  laravel:
    build:
      args:
        PHP_VERSION: ${PHP_VERSION}
        GIT_REPO_URL: ${GIT_REPO_URL}
        APP_NAME: ${APP_NAME}
        APP_UID: 1000
      context: ./
      dockerfile: php-dockerfiles/${PHP_VERSION}.dockerfile
    image: ${APP_NAME}-laravel
    container_name: ${APP_NAME}-laravel
    restart: unless-stopped
    working_dir: /var/www/${APP_NAME}
    environment:
      APP_NAME: ${APP_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - laravel-dir:/var/www/${APP_NAME}:delegated
      - ./config/laravel.env:/var/www/${APP_NAME}/.env:cached
      - ./entrypoints/php-entrypoint.sh:/usr/local/bin/docker-php-entrypoint:cached
      - ./entrypoints/db_checks.php:/usr/local/bin/db_checks.php:cached
    networks:
      - app-net
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${APP_NAME}-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - mysql-data:/var/lib/mysql:delegated
    networks:
      - app-net
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - ${PORT:-80}:80
    volumes:
      - laravel-dir:/var/www/${APP_NAME}:delegated
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:cached
    networks:
      - app-net
    depends_on:
      - laravel
